FROM dl_base

# Install Deep Learning environment
RUN pip --no-cache-dir install \
        https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl \
        torchvision \ 
        tensorflow==2.0.0-alpha0 \
        keras

RUN echo 'export PS1="\[\e[38;5;33m\](CPU DOCKER) \[\e[38;5;64m\]\W\e[00m\] $ "' >> ~/.bashrc
